name: ğŸ§ª Exercise 2 - Deploy with Secrets

on:
  workflow_dispatch:

jobs:
  deploy:
    name: ğŸš€ Deploy to DEVELOPMENT
    runs-on: ubuntu-latest
    environment: dev

    steps:
      - name: ğŸ Start Deployment
        run: echo "deploy to ${{ github.environment }}"

      - name: ğŸ”‘ Use Secret API Key
        env:
          MY_API_KEY: ${{ secrets.MY_API_KEY }}
        run: |
          echo "Using API key (masked): $MY_API_KEY"
