name: ğŸ§ª Exercise 1 - Dummy Deploy

on:
  workflow_dispatch:

jobs:
  deploy:
    name: ğŸš€ Deploy to DEVELOPMENT
    runs-on: ubuntu-latest
    environment: dev

    steps:
      - name: ğŸ Start Deployment
        run: echo "deploy to ${{ github.environment }}"
